#!/usr/bin/env ansible-playbook
---
- name: Run application test suite in CI.
  hosts: "app-{{ ci_env }}"
  become: yes
  tasks:
    - name: Execute wrapper script for application test suite.
      script: ../scripts/app-tests.sh "{{ app_dir[ci_env] }}"
      ignore_errors: true

      # The test results file will be posted as an artifact for the CI run,
      # so developers can download it and inspect it in detail.
    - name: Fetch JUnit test results XML file.
      fetch:
        src: /tmp/apptest.xml
        dest: ../../apptest-results.xml
        flat: yes
  vars:
    ci_env: "{{ lookup('env', 'CI_SD_ENV') }}" 
    # We must define this var at the play-level since the group/host vars
    # won't automatically be included, since they're relative to the
    # provisioning playbooks (rather than the CI bootstrapping playbooks).
    app_dir:
      staging: /var/www/securedrop
